### ISSUE TITLE
`unique` returns non-deterministic incorrect result on GPU.

### ISSUE THREAD

**Issue by trivialfis** [nv-legate/cunumeric#1028]
**Environment**
- nvcc: release 12.1, V12.1.105
- legate: 23.07.00.dev+49.gac75ac0
- cunumeric: '23.07.00.dev+44.g728d47db'
- python: Python 3.10.12
- numpy: 1.24.4

**script to reproduce**
``` python
import cunumeric as cn
import numpy as np

def test_unique() -> None:
    np.random.seed(1994)
    rng = cn.random.default_rng(1994)
    n_samples = 4096 * 64
    y = rng.integers(0, high=4, size=n_samples)
    uniques = cn.unique(y)
    print(uniques.shape, y.max(), y.min())
    n_uniques = uniques.shape[0]
    print(n_uniques)
```
launch:
```
legate --gpus=1
```

I ran this in a pytest environment twice, and the first result was correct:
```
(4,) 3 0
4
```
The second time however seems to be misbehaving:
```
(64358,) 3 0
64358
```

**Comment by manopapad** [comment]
Can you try printing out the first few elements from `uniques`, just to see what kinds of values end up in there?

Also, can you print out the size of the local result inside each invocation of the "unique" task, i.e. the value of `result.second` here https://github.com/nv-legate/cunumeric/blob/branch-23.09/src/cunumeric/set/unique.cu#L195? It might also be informative to `cudaMemcpy` the contents of `result.first` into a `malloc'd` buffer of sufficient size and print them out.

Depending on what these checks show, @mfoerste4 may have further suggestions. Since this is happening on a single GPU, this shouldn't even be touching the NCCL tree-reduce code, so it's more likely an issue with our kernels, our kernel launching, or the reporting of the output size back to the calling code.

**Comment by trivialfis** [comment]
Thank you for the reply! I will try to debug it next Monday.

**Comment by trivialfis** [comment]
After switching to 23.09 branch the issue is no longer reproducible. Thank you the help!
